
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_service_app
    container_name: user_service_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - user_service_network

  webserver:
    image: nginx:alpine
    container_name: user_service_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - user_service_network

  mysql:
    image: mysql:8.0
    container_name: user_service_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: UserIAE
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user_service_network

  redis:
    image: redis:alpine
    container_name: user_service_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - user_service_network

networks:
  user_service_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
